In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
for dirname, _, filenames in os.walk('bowling_odi.csv'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import plotly.express as px           # simple and easy to use
import plotly.graph_objects as go     # more control over the figure
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

# Bowling_odi

In [3]:
bowling_odi = pd.read_csv('t20.csv')
bowling_odi

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s,Unnamed: 15
0,0,V Kohli (INDIA),2010-2019,75,70,20,2633,94*,52.66,1907,138.07,0,24,2,247,71,NaN
1,1,RG Sharma (INDIA),2007-2019,104,96,14,2633,118,32.1,1905,138.21,4,19,6,234,120,NaN
2,2,MJ Guptill (NZ),2009-2019,83,80,7,2436,105,33.36,1810,134.58,2,15,2,215,113,NaN
3,3,Shoaib Malik (ICC/PAK),2006-2019,111,104,30,2263,75,30.58,1824,124.06,0,7,1,186,61,NaN
4,4,BB McCullum (NZ),2005-2015,71,70,10,2140,123,35.66,1571,136.21,2,13,3,199,91,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2001,1,SG Whittingham (SCOT),2018-2018,3,-,-,-,-,-,-,-,-,-,-,-,-,NaN
2002,2,LJ Woodcock (NZ),2010-2011,3,-,-,-,-,-,-,-,-,-,-,-,-,NaN
2003,3,Zamir Khan (AFG),2012-2012,1,-,-,-,-,-,-,-,-,-,-,-,-,NaN
2004,4,S Zargar (Mex),2019-2019,1,-,-,-,-,-,-,-,-,-,-,-,-,NaN
2005,5,Ziaur Rahman (AFG),2019-2019,1,-,-,-,-,-,-,-,-,-,-,-,-,NaN

# Exploratory Data Analysis

In [4]:
#Number of rows and Cols
bowling_odi.shape

(2006, 17)

In [5]:
#  fetch the first n rows
bowling_odi.head(20)

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s,Unnamed: 15
0,0,V Kohli (INDIA),2010-2019,75,70,20,2633,94*,52.66,1907,138.07,0,24,2,247,71,NaN
1,1,RG Sharma (INDIA),2007-2019,104,96,14,2633,118,32.1,1905,138.21,4,19,6,234,120,NaN
2,2,MJ Guptill (NZ),2009-2019,83,80,7,2436,105,33.36,1810,134.58,2,15,2,215,113,NaN
3,3,Shoaib Malik (ICC/PAK),2006-2019,111,104,30,2263,75,30.58,1824,124.06,0,7,1,186,61,NaN
4,4,BB McCullum (NZ),2005-2015,71,70,10,2140,123,35.66,1571,136.21,2,13,3,199,91,NaN
5,5,DA Warner (AUS),2009-2019,76,76,8,2079,100*,30.57,1476,140.85,1,15,5,203,86,NaN
6,6,EJG Morgan (ENG),2009-2019,86,84,17,2002,91,29.88,1475,135.72,0,11,3,151,96,NaN
7,7,Mohammad Shahzad (AFG),2010-2018,65,65,3,1936,118*,31.22,1436,134.81,1,12,3,218,72,NaN
8,8,JP Duminy (SA),2007-2019,81,75,25,1934,96*,38.68,1532,126.24,0,11,6,138,71,NaN
9,9,PR Stirling (IRE),2009-2019,72,71,6,1929,91,29.67,1401,137.68,0,16,8,233,59,NaN
10,10,Mohammad Hafeez (PAK),2006-2018,89,86,8,1908,86,24.46,1643,116.12,0,10,6,196,51,NaN
11,11,TM Dilshan (SL),2006-2016,80,79,12,1889,104*,28.19,1567,120.54,1,13,10,223,33,NaN
12,12,AJ Finch (AUS),2011-2019,58,58,9,1878,172,38.32,1200,156.5,2,11,4,182,90,NaN
13,13,LRPL Taylor (NZ),2006-2019,95,87,19,1743,63,25.63,1430,121.88,0,5,5,110,65,NaN
14,14,Umar Akmal (PAK),2009-2019,84,79,14,1690,94,26.0,1377,122.73,0,8,10,122,55,NaN
15,15,AB de Villiers (SA),2006-2017,78,75,11,1672,79*,26.12,1237,135.16,0,10,5,140,60,NaN
16,16,H Masakadza (ZIM),2006-2019,66,66,2,1662,93*,25.96,1418,117.2,0,11,1,151,65,NaN
17,17,AD Hales (ENG),2011-2019,60,60,7,1644,116*,31.01,1203,136.65,1,8,4,175,55,NaN
18,18,CH Gayle (WI),2006-2019,58,54,4,1627,117,32.54,1139,142.84,2,13,3,138,105,NaN
19,19,MS Dhoni (INDIA),2006-2019,98,85,42,1617,56,37.6,1282,126.13,0,2,1,116,52,NaN

In [6]:
#data types check
bowling_odi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2006 entries, 0 to 2005
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   2006 non-null   int64
 1   Player       2006 non-null   object
 2   Span         2006 non-null   object
 3   Mat          2006 non-null   int64
 4   Inns         2006 non-null   object
 5   NO           2006 non-null   object
 6   Runs         2006 non-null   object
 7   HS           2006 non-null   object
 8   Ave          2006 non-null   object
 9   BF           2006 non-null   object
 10  SR           2006 non-null   object
 11  100          2006 non-null   object
 12  50           2006 non-null   object
 13  0            2006 non-null   object
 14  4s           2006 non-null   object
 15  6s           2006 non-null   object
 16  Unnamed: 15  0 non-null      float64
dtypes: float64(1), int64(2), object(14)
memory usage: 266.5+ KB

In [7]:
#summary check
bowling_odi.describe()

        Unnamed: 0          Mat  Unnamed: 15
count  2006.000000  2006.000000          0.0
mean     24.434197    11.231805          NaN
std      14.463176    14.923332          NaN
min       0.000000     1.000000          NaN
25%      12.000000     3.000000          NaN
50%      24.000000     5.000000          NaN
75%      37.000000    13.000000          NaN
max      49.000000   111.000000          NaN

In [8]:
#check for null values
bowling_odi.columns[bowling_odi.isnull().any()], bowling_odi.isnull().sum()

(Index(['Unnamed: 15'], dtype='object'),
 Unnamed: 0        0
 Player            0
 Span              0
 Mat               0
 Inns              0
 NO                0
 Runs              0
 HS                0
 Ave               0
 BF                0
 SR                0
 100               0
 50                0
 0                 0
 4s                0
 6s                0
 Unnamed: 15    2006
 dtype: int64)

In [13]:
#delete unnamed: 0 column
bowling_odi = bowling_odi.drop(['Unnamed: 0', 'Unnamed: 13'], axis=1)
bowling_odi.head()

KeyError: "['Unnamed: 13'] not found in axis"